spring:
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/flat_rent
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE